name: Auto Fix Build Errors

on:
  workflow_run:
    workflows: ["Build Check"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write  # Required for OIDC token generation

jobs:
  auto-fix:
    # Only run if: (build failed and not auto-fix) OR manual trigger
    if: |
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'failure' &&
       !contains(github.event.workflow_run.head_commit.message, '[auto-fix]')) ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.ref || github.event.workflow_run.head_branch }}
          fetch-depth: 2 # Get last 2 commits for context

      - name: Get last commit info
        id: last_commit
        run: |
          echo "Last commit that triggered the build failure:"
          git log -1 --pretty=format:"Author: %an%nMessage: %s%nChanges:"
          
          # Handle case where there's only one commit
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            git diff HEAD~1 HEAD --stat
            
            # Save commit info for Claude
            git log -1 --pretty=format:"The build failed after this commit:%n%nAuthor: %an%nMessage: %s%n" > commit_context.txt
            echo -e "\nFiles changed:" >> commit_context.txt
            git diff HEAD~1 HEAD --name-only >> commit_context.txt
          else
            echo "This is the first commit on the branch"
            git log -1 --pretty=format:"The build failed on this first commit:%n%nAuthor: %an%nMessage: %s%n" > commit_context.txt
            echo -e "\nAll files in this commit:" >> commit_context.txt
            git ls-tree --name-only -r HEAD >> commit_context.txt
          fi

      - name: Fix build errors with Claude
        uses: anthropics/claude-code-action@beta
        with:
          direct_prompt: |
            The build is failing. Based on the recent commit changes in commit_context.txt,
            identify and fix any TypeScript errors, ESLint violations, or import issues.

            Run 'pnpm build' and 'pnpm lint' to verify your fixes work.
            Make minimal changes - only fix what's broken.
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          mode: agent
          max_turns: 20
          timeout_minutes: 10

      - name: Commit and push if changes exist
        run: |
          if [[ -n $(git diff --stat) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "fix: build errors [auto-fix]

            Automated fix triggered by workflow run #${{ github.event.workflow_run.run_number }}"
            git push

            echo "✅ Pushed fixes to ${{ github.event.workflow_run.head_branch }}"
          else
            echo "❌ No changes made - Claude couldn't fix the errors automatically"
            exit 1
          fi
